# Generated by Django 4.0.6 on 2022-07-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=69)),
                ('email', models.EmailField(max_length=256)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
